export async function getServerSideProps({ res }) {
  const base = process.env.NEXT_PUBLIC_URL || 'https://hemguiden.vercel.app';
  const pages = [{"path":"","priority":"1.0","changefreq":"daily"},{"path":"/om-oss","priority":"0.5","changefreq":"monthly"},{"path":"/kontakt","priority":"0.4","changefreq":"monthly"},{"path":"/integritetspolicy","priority":"0.3","changefreq":"yearly"},{"path":"/student","priority":"0.8","changefreq":"weekly"},{"path":"/villa","priority":"0.8","changefreq":"weekly"},{"path":"/bostadsratt","priority":"0.8","changefreq":"weekly"},{"path":"/hyresratt","priority":"0.8","changefreq":"weekly"},{"path":"/utan-bindningstid","priority":"0.8","changefreq":"weekly"},{"path":"/billigast","priority":"0.8","changefreq":"weekly"},{"path":"/jamfor/folksam-vs-lansforsakringar","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/folksam-vs-trygg-hansa","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/folksam-vs-if-skadeforsakring","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/folksam-vs-moderna-forsakringar","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/folksam-vs-dina-forsakringar","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/folksam-vs-ica-forsakring","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/lansforsakringar-vs-trygg-hansa","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/lansforsakringar-vs-if-skadeforsakring","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/lansforsakringar-vs-moderna-forsakringar","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/lansforsakringar-vs-dina-forsakringar","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/lansforsakringar-vs-ica-forsakring","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/trygg-hansa-vs-if-skadeforsakring","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/trygg-hansa-vs-moderna-forsakringar","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/trygg-hansa-vs-dina-forsakringar","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/trygg-hansa-vs-ica-forsakring","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/if-skadeforsakring-vs-moderna-forsakringar","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/if-skadeforsakring-vs-dina-forsakringar","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/if-skadeforsakring-vs-ica-forsakring","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/moderna-forsakringar-vs-dina-forsakringar","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/moderna-forsakringar-vs-ica-forsakring","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/dina-forsakringar-vs-ica-forsakring","priority":"0.7","changefreq":"weekly"}];
  const xml = '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' +
    pages.map(function(p) { return '<url><loc>'+base+p.path+'</loc><lastmod>2026-06-24</lastmod><changefreq>'+p.changefreq+'</changefreq><priority>'+p.priority+'</priority></url>'; }).join('') +
    '</urlset>';
  res.setHeader('Content-Type', 'application/xml');
  res.setHeader('Cache-Control', 's-maxage=86400, stale-while-revalidate');
  res.write(xml); res.end();
  return { props: {} };
}
export default function Sitemap() { return null; }